### ISSUE TITLE
Connection to Wrangler ?

### ISSUE THREAD

**Issue by SheepDomination** [melMass/vscode-vex#1]
Will there be a connection between a Wrangler Node & this extension for Visual Studio Code coming so one can send code from Visual Studio Code to the wrangler or vise versa ?

**Comment by cgtoolbox** [comment]
Have a look on that script:
http://cgtoolbox.com/houdini-expression-editor/

I show how you can use VS code + vex highlight to update your wrangle without freezing Houdini.

**Comment by SheepDomination** [comment]
Oh your Guillamne, Hi.
