### ISSUE TITLE
Better Comments in VEX Extension

### ISSUE THREAD

**Issue by SheepDomination** [melMass/vscode-vex#2]
Hi, I was hoping you communicate with the author of the extension Better Comments to add the comment feature into this VEX extension.

**Comment by melMass** [comment]
Never tried it before, it looks promising. 
I'll definitely check what are our options and get back to you here.

**Comment by melMass** [comment]
It actually look pretty simple to add custom languages.
I'll pull request the vex support this week.
Thanks for the idea.

**Comment by SheepDomination** [comment]
No problem, and if you can give me a follow up. I'm currently in the process of trying to tailor *better comments* ;)

**Comment by melMass** [comment]
So I have tried Better Comments and don't see any advantages over [todo-highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) which I use and is language agnostic. 
What do you think ?

**Comment by SheepDomination** [comment]
Sorry, do you know how to trigger the comments ?
