### ISSUE TITLE
[Suggestion] Add more Functions descriptions

### ISSUE THREAD

**Issue by Leroy-X** [melMass/vscode-vex#4]
I test VSCode and Sublime text, and I find in sublime have much more functions descriptions, but in vscode just one, if possible, hope to add more option in same function, sorry my poor English, you can see the image in flow.
![vscode](https://user-images.githubusercontent.com/13515498/42446280-45a50176-83a8-11e8-9aed-f8c8b683c813.png)
![sublime](https://user-images.githubusercontent.com/13515498/42446283-4a1ee5c8-83a8-11e8-9831-b7e00f2aeb01.png)

**Comment by melMass** [comment]
Hi @Leroy-X 

This is, in fact, missing some signatures you are right.
@wecurse seems to be willing to give it a go (#5 ).
I'll work on it on my side as well
