### ISSUE TITLE
shader support?

### ISSUE THREAD

**Issue by JianwenGo** [melMass/vscode-vex#6]
Does vscode-vex supports shader edit?
And I am wondering how to open vscode as external editor for shader editing 
(modifying the houdini.env?) 
thanks for the great plugin :)

**Comment by melMass** [comment]
It should work for shaders. What is your issue ?
I might add specific shader features on request, I must admit that I don't use Vex Shaders. 

For linking with an external editor you can use Cetras `Houdini Expr Editor`, it is a fork of https://github.com/ArthurYidi/Houdini-External-Editor but unlike the original it's non blocking, meaning you just need to save in the editor to update the wrangle node in Houdini !

https://vimeo.com/242470411

**Comment by melMass** [comment]
I'm closing this issue as I haven't heard back from you. Don't hesitate to open a new one.
