### ISSUE TITLE
Add new VEX functions.

### ISSUE THREAD

**Issue by antoniopepe82** [melMass/vscode-vex#7]
new VEX function for Houdini 18 .. any upgrade ?

thanks for your time

**Comment by AKA009** [comment]
need upgrade +1, please

**Comment by melMass** [comment]
Hi @antoniopepe82  @AKA009, I started a full rewrite a year ago but never had the time to polish it for release.

I will look into adding the new H18 functions to the version on this repo in the weekend, thanks for the reminder. And I think V2 will be done next month.

**Comment by AKA009** [comment]
> Hi @antoniopepe82 @AKA009, I started a full rewrite a year ago but never had the time to polish it for release.
> 
> I will look into adding the new H18 functions to the version on this repo in the weekend, thanks for the reminder. And I think V2 will be done next month.

Thank you and by the way, there are full intelligence data of all VEX functions at `$Your houdini install path\houdini\help\vex.zip\functions`

**Comment by antoniopepe82** [comment]
great news... Thanks for your time !

**Comment by melMass** [comment]
Done! the new version is already starting to work pretty well :)

**Comment by antoniopepe82** [comment]
> Done! the new version is already starting to work pretty well :)

Fantastico.
